### ISSUE TITLE
Problem 2 of AMG not correctly parsing Cumulative Number of Iterations

### ISSUE THREAD

**Issue by jennfshr** [ArtistMonkey83/PavilionTestHarness#3]
@ArtistMonkey83 @ckendric @quezadaa 
If we're gonna keep the problem2.out redirection, then, we'll need a `files: 'problem2.out'` specifier on the iterations key under result_parse. 

```yaml
        regex:
            iterations:
                files: 'problem2.out'
                regex: 'Cum. No. of Iterations = (\d+)'
                action: store
            fom_2:
                files: 'problem2.out'
                regex: 'Figure\s+of\s+Merit\s+\(FOM_2\):\s+([\S]+)'
                action: store
```
right now, the iterations aren't getting set, thus, `pav results -f` shows Iterations: None.
