### ISSUE TITLE
Need to use threading in the AMG test execution

### ISSUE THREAD

**Issue by jennfshr** [ArtistMonkey83/PavilionTestHarness#6]
Improved performance when running with OMP_NUM_THREADS set.  
The Makefile compiles the OMP support for AMG, but we're not running with it. Here are the differences in performance - orders of magnitude improvement for the run with OMP_NUM_THREADS=2 over not setting the env var OMP_NUM_THREADS at all.
```
# with OMP_NUM_THREADS exported to '2'
 'amg.amg.problem2x4': {'created': '2020-06-30 10:49:34.952791',
                        'duration': '0:00:04.132588',
                        'fom': '4.811347e+08',
                        'id': 6161,
                        'iterations': '213',
                        'name': 'amg.amg.problem2x4',
                        'numthreads': '2',
                        'nx': '40',
                        'ny': '40',
                        'nz': '40',
                        'pav_result_errors': [],
                        'problem': 'problem2x4',
                        'px': '2',
                        'py': '2',
                        'pz': '1',
                        'result': 'PASS',
```
```
# without setting OMP_NUM_THREADS whatsoever
 'amg.amg.problem2x4': {'created': '2020-06-30 10:59:31.221842',
                        'duration': '0:05:35.230716',
                        'fom': '4.771029e+06',
                        'id': 6167,
                        'iterations': '213',
                        'name': 'amg.amg.problem2x4',
>>this is why we're seeing a performance hit, without setting OMP_NUM_THREADS to a reasonable value, it's trying to run 36!
                        'numthreads': '36',
<<
                        'nx': '40',
                        'ny': '40',
                        'nz': '40',
                        'problem': 'problem2x4',
                        'px': '2',
                        'py': '2',
                        'pz': '1',
                        'result': 'PASS',
```
to enable threading, do this:
```yaml
    run:
    env:
        OMP_NUM_THREADS: '2'
        OMP_DISPLAY_ENV: 'VERBOSE'
``` 
and to capture that in results, do this:
```yaml
        regex:
            <other keys regex here> 
            numthreads:
                regex: "OMP_NUM_THREADS = \'(\d+)\'"
                action: store
                files: '{{problem.name}}.out'
```
![image](https://user-images.githubusercontent.com/850386/86155234-5c681180-bac1-11ea-8f36-8139c340b527.png)
